name: Build and Deploy Shiny App to AWS

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  pull_request:
    branches:
      - main

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Set up AWS CLI and Docker
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -f Dockerfile -t phenology-website:latest .

    # Step 4: Log in to AWS ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 861486687156.dkr.ecr.us-east-2.amazonaws.com

    # Step 5: Tag the Docker image
    - name: Tag Docker image
      run: |
        docker tag phenology-website:latest 861486687156.dkr.ecr.us-east-2.amazonaws.com/phenology-website:latest

    # Step 6: Push Docker image to AWS ECR
    - name: Push Docker image to ECR
      run: |
        docker push 861486687156.dkr.ecr.us-east-2.amazonaws.com/phenology-website:latest

    # Step 7: Deploy to AWS App Runner
    - name: Deploy to App Runner
      run: |
        aws apprunner update-service \
          --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website/a4fe8389d6a744ada162975c0e3157b5 \
          --source-configuration '{"ImageRepository": {"ImageRepositoryType": "ECR","ImageIdentifier": "861486687156.dkr.ecr.us-east-2.amazonaws.com/phenology-website:latest","ImageConfiguration": {"Port": "3838"}}}'
